language: python
python:
  - '2.7_with_system_site_packages'
  - 2.6
before_install:
  - sudo apt-get update
  # For Python 2.7, install PyQt4
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7_with_system_site_packages' ]]; then source .travis_before_install; fi
  # PyQt can't be installed on 2.6; run the tests without Qt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then source .travis_before_install_noqt; fi
  - sudo apt-get install swig
  # Simlinks for PIL compilation
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libfreetype.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libjpeg.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libpng.so /usr/lib/
  - sudo ln -s /usr/lib/`uname -i`-linux-gnu/libz.so /usr/lib/
install:
  # nose is already installed
  - pip install cython
  - pip install --upgrade numpy
  - pip install -r dev_requirements.txt
  - wget -nv http://cairographics.org/releases/py2cairo-1.10.0.tar.bz2
  - tar -xf py2cairo-1.10.0.tar.bz2
  - pushd py2cairo-1.10.0
  - ./waf configure
  - ./waf build
  - sudo ./waf install
  - popd
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run -m nose.core -v enable/tests
  - coverage run -a -m nose.core -v enable/savage/svg/tests
  - coverage run -a -m nose.core -v kiva/tests
  - coverage run -a -m nose.core -v kiva/agg/tests
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
