language: python
sudo: false
python:
  - '2.7_with_system_site_packages'
  - 2.6
env:
  - ETS_TOOLKIT=wx REQUIREMENTS=dev_requirements_pillow.txt
  - ETS_TOOLKIT=qt4 REQUIREMENTS=dev_requirements_pillow.txt
  - ETS_TOOLKIT=null.image REQUIREMENTS=dev_requirements_pillow.txt
  - ETS_TOOLKIT=null.image REQUIREMENTS=dev_requirements_pil.txt
matrix:
  exclude:
    - python: 2.6
      env: ETS_TOOLKIT=qt4 REQUIREMENTS=dev_requirements_pillow.txt
    - python: 2.6
      env: ETS_TOOLKIT=wx REQUIREMENTS=dev_requirements_pillow.txt
before_install:
  - sh ./travis_setup.sh
  # setup X11 for the tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # nose is already installed
  # numpy is already installed
  - pip install -r $REQUIREMENTS
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run -m nose.core -v enable/tests
  - coverage run -a -m nose.core -v enable/savage/svg/tests
  - coverage run -a -m unittest2 discover -v -p *test_* kiva/tests
  - coverage run -a -m nose.core -v kiva/agg/tests
after_success:
  coveralls
