language: python
python:
  - '2.7_with_system_site_packages'
  - 2.6
before_install:
  # For Python 2.7, install PyQt4
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7_with_system_site_packages' ]]; then source .travis_before_install; fi
  # PyQt can't be installed on 2.6; run the tests without Qt
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then source .travis_before_install_noqt; fi
  - sudo apt-get install python-numpy
  - sudo apt-get install swig
install:
  # nose is already installed
  - pip install cython
  - git clone https://github.com/nucleic/kiwi
  - pushd
  - cd kiwi/py
  - python ./build.py install
  - popd
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run -m nose.core -v enable/tests
  - coverage run -a -m nose.core -v enable/savage/svg/tests
  - coverage run -a -m nose.core -v kiva/tests
  - coverage run -a -m nose.core -v kiva/agg/tests
notifications:
  email:
    - travis-ci@enthought.com
after_success:
  coveralls
