language: python
python:
  - 2.7
  - 2.6
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
before_install:
  # Install PyQt4 and run the UI tests
  - source .travis_before_install
install:
  # nose is already installed
  - pip install cython
  - sudo apt-get install python-numpy
  - sudo apt-get install swig
  - pip install PIL
  - pip install pyparsing
  # Test against the current master of traits and traitsui
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install git+http://github.com/enthought/traitsui.git#egg=traitsui
  - python setup.py develop
script: nosetests
notifications:
  email:
    - travis-ci@enthought.com