language: python
sudo: false
python:
  - '2.7_with_system_site_packages'
  - 2.6
addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - python-qt4-gl
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
    - swig
    - zlib1g-dev
    - libpng-dev
    - libfreetype6-dev
    - python-cairo
env:
  - ETS_TOOLKIT=wx
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=null.image PILLOW='pillow<3.0.0'
matrix:
  exclude:
    - python: 2.6
      env: ETS_TOOLKIT=qt4
    - python: 2.6
      env: ETS_TOOLKIT=wx
    - python: 2.6
      env: ETS_TOOLKIT=wx ETS_TOOLKIT=null.image PILLOW='pillow'
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  # setup X11 for the tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # Install pillow separately to control the version
  - pip install $PILLOW
  - pip install -r travis-ci-requirements
  - pip install coveralls
  - python setup.py develop
script:
  - coverage run -m nose.core -v enable/tests
  - coverage run -a -m nose.core -v enable/savage/svg/tests
  - coverage run -a -m unittest2 discover -v -p *test_* kiva/tests
  - coverage run -a -m nose.core -v kiva/agg/tests
after_success:
  - pip install codecov
  - codecov