language: python
python:
  - 2.7
  - 3.3
  - 3.4

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export ETS_TOOLKIT=qt4
  - 'export LD_LIBRARY_PATH=`python -c "import os,nose; print(os.path.dirname(os.path.dirname(nose.__file__)))"`/PySide'
install:
  - sudo apt-get install swig

  - pip install -U nose
  - pip install Numpy
  - pip install Cython
  - pip install Pillow
  - pip install PyParsing

  # PySide from a wheel
  - git clone https://github.com/pradyun/travis-dependencies dependencies
  - pip install -v -v -v --no-index --find-links=./dependencies PySide

  # Test against the current master of traits and traitsui
  - pip install git+http://github.com/enthought/traits.git#egg=traits
  - pip install git+http://github.com/pradyun/pyface.git@python3#egg=pyface
  - pip install git+http://github.com/pradyun/traitsui.git@python3#egg=traitsui

  - python setup.py build
  - python setup.py develop

  - pip install coverage
  - pip install coveralls

before_script:
  - export NOSE_WITH_COVERAGE=True
script:
  - python setup.py nosetests --cover-package enable --cover-package kiva --tests kiva.tests
  - python setup.py nosetests --cover-package enable --cover-package kiva --tests kiva.agg.tests
  - python setup.py nosetests --cover-package enable --cover-package kiva --tests enable.tests
  - python setup.py nosetests --cover-package enable --cover-package kiva --tests enable.savage.svg.tests
after_success:
  - coveralls

notifications:
  email:
    - travis-ci@enthought.com
