language: python
sudo: false
python:
  - '2.7_with_system_site_packages'
  - 3.4
addons:
  apt:
    packages:
    - python-qt4
    - python-qt4-dev
    - python-qt4-gl
    - python-pip
    - python-numpy
    - python-wxtools
    - ccache
    - cmake
    - swig
    - zlib1g-dev
    - libpng-dev
    - libfreetype6-dev
    - python-cairo
env:
  - ETS_TOOLKIT=wx
  - ETS_TOOLKIT=qt4
  - ETS_TOOLKIT=null.image
matrix:
  exclude:
    - python: 3.4
      env: ETS_TOOLKIT=wx
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - pip install --upgrade pip
  - if [[ ${TRAVIS_PYTHON_VERSION} == "3.4" && ${ETS_TOOLKIT} == "qt4" ]]; then ./build_pyside_wheel.sh; fi
  # setup X11 for the tests
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  # nose is already installed
  # numpy is already installed
  - pip install -r travis-ci-requirements
  - python setup.py develop
before_script:
  - cp .coveragerc integrationtests/kiva/agg
  - cd integrationtests/kiva/agg
script:
  - coverage run -m nose.core enable -v
  - coverage run -a -m nose.core kiva -v
  - coverage run -a -m nose.core -v --no-capture
after_success:
  - pip install codecov
  - codecov
